### PR TITLE
Docker-compose

### PR DESCRIPTION
**Pull request by easauceda**

### CODE REVIEW

**Comment by mmckelvy** [comment]
@easauceda is this still active?

**Comment by easauceda** [comment]
@mmckelvy Yeah I'd like to get it merged in, just going to add a quick update to the makefile

**Comment by tphummel** [comment]
this looks great. any reasons not to merge? @AlecAivazis @jsjaspreet @mmckelvy @easauceda

**Comment by tphummel** [comment]
test

**Comment by easauceda** [comment]
Going to merge this if there's no objections @AlecAivazis @jsjaspreet @mmckelvy

**Comment by AlecAivazis** [comment]
LGTM - :shipit:

**Pull request merged**
